version: "3"

services:
  flask-app:
    container_name: markdown-connector         # ğŸ‘ˆ è‡ªå®šä¹‰å®¹å™¨åç§°
    build: .
    ports:
      - "1313:5000"
    volumes:
      - /Users/xu/Desktop/blog/aaa:/app/markdown
    restart: always
